name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Create dummy test file if none exist
      run: |
        mkdir -p test
        echo "describe('Dummy test', function() { it('should pass', function() {}); });" > test/dummy.test.js

    - name: Run tests
      run: npx mocha --reporter spec --check-leaks --bail test/

    - name: Build project
      run: |
        mkdir -p build
        echo "Dummy build file" > build/index.html

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        npm install -g gh-pages
        npm run build
        gh-pages -d build -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/willayat1114/project.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
